version: "3.7"

services:
  dwg-alerter:
    build:
      context: .
      dockerfile: apps/dwg-alerter/Dockerfile
    container_name: dwg-alerter
    env_file: .env
    environment:
      - ALERTS_FILE_PATH=/data/alerts.json
    volumes:
      - alerter-data:/data
  operators-ping:
    build:
      context: .
      dockerfile: apps/operators-ping/Dockerfile
    container_name: operators-ping
    env_file: .env
    environment:
      - TEST_INTERVAL_MIN=5

volumes:
  alerter-data:
